### ISSUE TITLE
Text prediction

### ISSUE THREAD

**Issue by lightningRalf** [HazyResearch/TART#1]
First of all, thanks for your insights presented in this paper.

Are there any plans to introduce also a notebook for text prediction?
Would be very interested in trying this on the prediction side of things.

Of course this part would have to have different datasets.

Thanks in advance.

**Comment by kgourgou** [comment]
By text prediction, do you perhaps mean "text generation"? 

The paper states: 

> In future work, we seek to understand whether synthetic tasks exist for
training other generic reasoning modules, capable of improving base LLM performance on tasks such
as **generation** or summarization.

So that seems like an open problem.

**Comment by ANarayan** [comment]
Yup! To @kgourgou's point, we hope to extend the method to text generation soon. If you'd like to try TART for classification, checkout this notebook: https://github.com/HazyResearch/TART/blob/main/src/notebooks/text-classification.ipynb
